### ISSUE TITLE
Franca Import

### ISSUE THREAD

**Issue by gmalmeida** [franca/franca#170]
@kbirken sorry to disturb again...

after importing the project on Eclipse, I get lots of compilation errors, I am afraid I have missed some configuration step during setup. Can you help there?

![franca_eclipse_import_error](https://cloud.githubusercontent.com/assets/5320909/10431039/f359b476-7102-11e5-9967-c0bd1da3d17c.png)

> For all features, you may install the SDK version instead the non-SDK version in order to additionally get the source code (useful for debugging and diving deeper into the Franca implementation).

Where can I find the SDK version?

**Comment by kbirken** [comment]
All the "Bundle ... cannot be resolved" errors indicate that the installation of Xtext, Xtend, Franca and various other bundles have not been successful. These are the dependencies required by the Franca example project as of the MANIFEST.MF file. 

Did you follow the Quick Install Guide step-by-step (see https://github.com/franca/franca/wiki/Franca-Quick-Install-Guide)?

You might start debugging by opening "Help > Installation Details..." and checking the "Plug-Ins" tab. The bundles mentioned in the "Problems" view should be visible there.

**Comment by gmalmeida** [comment]
yes Klaus, I have followed the instructions step-by-step... I have been to Plug-Ins tabs, and I see the bundles over there... so I do not understand the problem...

In the guide you mention:

> For all features, you may install the SDK version instead the non-SDK version in order to additionally get the source code (useful for debugging and diving deeper into the Franca implementation).

However there is no information where can I find the SDK version? could you please point me to that?

Thx

**Comment by kbirken** [comment]
Sorry, I forgot to respond to that part of your question. Each Franca feature is offered in a purely binary version or in a version including the source code (for debugging). The source-code version is referred to as "SDK version". When you are installing Franca from the update site or from an archive, you will be offered both versions of each feature. You should have already seen this choice when installing Franca.

Regarding your plug-in problem: Maybe there is some inconsistency in your Eclipse configuration and the plug-ins do not get started. You might look for error messages in the "Errors" view  or in the Eclipse logfile (which you can find in your workspace, file .metadata/.log). But usually the Quick Install procedure should work without flaw.

**Comment by gmalmeida** [comment]
Below the screenshot of the installed packages... maybe I am missing any? 

![franca_eclipse_installed_packages](https://cloud.githubusercontent.com/assets/5320909/10482979/be66a960-727c-11e5-9e3e-d3698a9067e7.png)

**Comment by kbirken** [comment]
This looks fine. Have you checked the "Plug-ins" tab and the ./metadata/.log, too? Maybe something elementary is missing and the actual Franca, Xtext or Xtend bundles couldn't be started (e.g., some org.eclipse.core or org.eclipse.emf plug-in)?

One more check: Can you open or create a file with *.xtend extension and get the usual Xtend editor (with syntax highlighting etc)

If you do not find any hint, you should maybe just repeat the installation. You could try to install a minimal installation first without the D-Bus support, the "Franca UI Add-ons", and the KIELER framework.

**Comment by gmacario** [comment]
Or maybe try https://github.com/gunnarx/franca_install_automation helps creating a stable Franca tool installation

**Comment by gmalmeida** [comment]
@kbirken  Log file below...
@gmacario Thanks for the link, is it only possible by setting up virutalmachines or would be also possible to run it to setup Franca on windows?   

```

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 13:10:13.466
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 13:10:13.466
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 13:10:13.466
!MESSAGE "Franca Runtime" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 13:10:13.472
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 13:10:13.472
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 13:10:13.472
!MESSAGE "Franca Runtime" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 13:28:20.449
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 13:28:20.449
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 13:28:20.449
!MESSAGE "Franca UI" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 13:28:20.453
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 13:28:20.454
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 13:28:20.454
!MESSAGE "Franca UI" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 13:56:43.548
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 13:56:43.548
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 13:56:43.548
!MESSAGE "Franca User Interface Add-ons" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 13:56:43.552
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 13:56:43.552
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 13:56:43.552
!MESSAGE "Franca User Interface Add-ons" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 14:04:32.503
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 14:04:32.503
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 14:04:32.503
!MESSAGE "Franca Runtime SDK" will be ignored because it is already installed.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2015-10-14 14:04:32.506
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10050 2015-10-14 14:04:32.506
!MESSAGE Cannot complete the request.  See the error log for details.
!SUBENTRY 1 org.eclipse.equinox.p2.operations 2 10005 2015-10-14 14:04:32.506
!MESSAGE "Franca Runtime SDK" will be ignored because it is already installed.
!SESSION 2015-10-14 12:49:57.464 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.dsl.product

!ENTRY org.eclipse.egit.ui 2 0 2015-10-14 14:05:06.115
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\GAlmeida'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2015-10-14 14:06:23.076
!MESSAGE No repository found at jar:file:/D:/Franca/org_franca_examples_src_2015-07-29.zip!/.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2015-10-14 14:06:26.003
!MESSAGE No repository found at http://download.eclipse.org/graphiti/updates/0.8.1.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2015-10-14 14:06:44.789
!MESSAGE No repository found at jar:file:/D:/Franca/site_franca_0.10.0.201507291433.zip!/.

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2015-10-14 14:06:57.313
!MESSAGE No repository found at jar:file:/D:/Franca/installer/site_franca_0.10.0.201507291433/artifacts.jar!/.
!SESSION 2015-10-15 10:55:57.032 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.dsl.product

!ENTRY org.eclipse.egit.ui 2 0 2015-10-15 10:56:35.738
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\GAlmeida'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.equinox.p2.core 4 0 2015-10-15 10:57:06.130
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at http://download.itemis.de/updates/releases/compositeContent.xml.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:192)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.getLocalFile(CompositeMetadataRepositoryFactory.java:73)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:98)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:166)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:106)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:122)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:151)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:129)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:73)
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2015-10-15 10:57:06.135
!MESSAGE Unable to read repository at http://download.itemis.de/updates/releases/compositeContent.xml.
!STACK 0
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.metadata.repository 4 1000 2015-10-15 10:57:06.225
!MESSAGE No repository found at jar:file:/D:/Franca/org_franca_examples_src_2015-07-29.zip!/.

!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2015-10-15 10:57:06.255
!MESSAGE Connection to http://download.eclipse.org/graphiti/updates/0.8.1/p2.index failed on Address already in use: JVM_Bind. Retry attempt 0 started
!STACK 0
java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.Socket.bind(Unknown Source)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient4.ECFHttpClientProtocolSocketFactory.connectSocket(ECFHttpClientProtocolSocketFactory.java:82)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2015-10-15 10:57:06.615
!MESSAGE Unable to read repository at http://download.eclipse.org/graphiti/updates/0.8.1/content.xml.
!STACK 0
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2015-10-15 10:57:11.003
!MESSAGE Connection to http://guava-osgi.googlecode.com/svn/trunk/repository/p2.index failed on Address already in use: JVM_Bind. Retry attempt 0 started
!STACK 0
java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.Socket.bind(Unknown Source)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient4.ECFHttpClientProtocolSocketFactory.connectSocket(ECFHttpClientProtocolSocketFactory.java:82)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2015-10-15 10:57:11.319
!MESSAGE Unable to read repository at http://guava-osgi.googlecode.com/svn/trunk/repository/content.xml.
!STACK 0
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2015-10-15 10:57:11.348
!MESSAGE Connection to http://download.itemis.com/updates/releases/p2.index failed on Address already in use: JVM_Bind. Retry attempt 0 started
!STACK 0
java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.Socket.bind(Unknown Source)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient4.ECFHttpClientProtocolSocketFactory.connectSocket(ECFHttpClientProtocolSocketFactory.java:82)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2015-10-15 10:57:11.681
!MESSAGE Unable to read repository at http://download.itemis.com/updates/releases/compositeContent.xml.
!STACK 0
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2015-10-15 10:57:12.569
!MESSAGE Connection to http://download.eclipse.org/releases/luna/p2.index failed on Address already in use: JVM_Bind. Retry attempt 0 started
!STACK 0
java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.Socket.bind(Unknown Source)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient4.ECFHttpClientProtocolSocketFactory.connectSocket(ECFHttpClientProtocolSocketFactory.java:82)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```

**Comment by gmacario** [comment]
@gmalmeida

> Is it only possible by setting up virutalmachines or would be also possible to run it to setup Franca on windows?

Well, so far I have only tried https://github.com/gunnarx/franca_install_automation to create a VirtualBox VM on a Windows hosting. 

Concerning a native install of Franca on Windows I do not know. @gunnarx?

**Comment by gmalmeida** [comment]
@gmacario, your script works like a charm... thanks for the hint... 

setup ready to play :+1:
