### ISSUE TITLE
Contract Viewer error in Eclipse: Can't view diagram (Unhandled event loop exception)

### ISSUE THREAD

**Issue by LIII-XXII** [franca/franca#196]
Hi all,

I am trying to setup Franca using the [Quick Install Guide](https://github.com/franca/franca/wiki/Franca-Quick-Install-Guide), and trying to get the contract view for the basic examples (org.franca.examples.basic)

I get the same error in both Linux (Ubuntu 14.04 virtual machine) and Windows 7.
My Eclipse version: Eclipse DSL Tools Version: Mars.2 Release (4.5.2) Build id: 20160218-0600
I also tried in Eclipse Neon (on Windows) and got the same problem.
This error does not appear without the Contract Viewer (User Interface Add-Ons + Kieler Lightweight diagrams).

**Installed packages:**

-   D-Bus Model Feature	0.8.1.201606031239	model.emf.dbusxml.feature.feature.group	itemis AG
-   Eclipse DSL Tools	4.5.2.20160218-0600	epp.package.dsl	null
-   Franca D-Bus support	0.11.0.201607111218	org.franca.dbus.feature.group	itemis AG
-   Franca D-Bus support SDK	0.11.0.201607111218	org.franca.dbus.sdk.feature.group	itemis AG
-   Franca D-Bus support UI	0.11.0.201607111218	org.franca.dbus.ui.feature.group	itemis AG
-   Franca D-Bus support UI SDK	0.11.0.201607111218	org.franca.dbus.ui.sdk.feature.group	itemis AG
-   Franca Runtime	0.11.0.201607111218	org.franca.core.feature.group	itemis AG
-   Franca Runtime SDK	0.11.0.201607111218	org.franca.core.sdk.feature.group	itemis AG
-   Franca UI	0.11.0.201607111218	org.franca.ui.feature.group	itemis AG
-   Franca UI SDK	0.11.0.201607111218	org.franca.ui.sdk.feature.group	itemis AG
-   Franca User Interface Add-ons SDK	0.11.0.201607111218	org.franca.ui.addons.sdk.feature.group	itemis AG
-   KIELER Lightweight Diagrams - Developer Resources & Examples	0.8.0.201602161004	de.cau.cs.kieler.klighd.sdk.feature.feature.group	Kiel University

**This Unhandled event loop exception is raised as soon as Eclipse is started:**
```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.dsl.product

org.eclipse.ui
Error
Thu Aug 11 16:37:59 CEST 2016
Unhandled event loop exception

java.lang.NoClassDefFoundError: Could not initialize class de.cau.cs.kieler.klighd.KlighdDataManager
	at de.cau.cs.kieler.klighd.ui.internal.handlers.KlighdActionExecutionHandler$IActionParameterValueConverter.convertToObject(KlighdActionExecutionHandler.java:163)
	at org.eclipse.ui.internal.commands.ParameterValueConverterProxy.convertToObject(ParameterValueConverterProxy.java:63)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.convertParameterValue(HandlerServiceImpl.java:140)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.addParms(HandlerServiceImpl.java:117)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.canExecute(HandlerServiceImpl.java:174)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:217)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerShowProcessor.showMenu(MenuManagerShowProcessor.java:230)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerShowProcessor.menuAboutToHide(MenuManagerShowProcessor.java:110)
	at org.eclipse.jface.internal.MenuManagerEventHelper.showEventPostHelper(MenuManagerEventHelper.java:92)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:467)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:461)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:493)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:255)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1334)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:198)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:3861)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3420)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**This is the error in the Diagram View:**

```
Plug-in "de.cau.cs.kieler.klighd.ui.view" was unable to instantiate class "de.cau.cs.kieler.klighd.ui.view.DiagramView".
org.eclipse.core.runtime.CoreException: Plug-in "de.cau.cs.kieler.klighd.ui.view" was unable to instantiate class "de.cau.cs.kieler.klighd.ui.view.DiagramView".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:188)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.registry.ViewDescriptor.createView(ViewDescriptor.java:58)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:101)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:279)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:525)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:509)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:69)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:104)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4633)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:572)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:536)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:701)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:639)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:634)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1157)
	at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1276)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1267)
	at org.eclipse.ui.internal.WorkbenchPage$12.run(WorkbenchPage.java:4238)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4234)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4214)
	at org.eclipse.ui.handlers.ShowViewHandler.openView(ShowViewHandler.java:127)
	at org.eclipse.ui.handlers.ShowViewHandler.openOther(ShowViewHandler.java:110)
	at org.eclipse.ui.handlers.ShowViewHandler.execute(ShowViewHandler.java:77)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.internal.ShowViewMenu$3.run(ShowViewMenu.java:147)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/elk/graph/properties/IPropertyHolder
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	... 117 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.elk.graph.properties.IPropertyHolder cannot be found by de.cau.cs.kieler.klighd.ui.view_0.3.0.201607290806
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 122 more
```

Best regards

**Comment by kbirken** [comment]
In our test installation, the contract viewer works fine. Your installation resembles our test environment with two differences:

1. You are using Eclipse DSL Tools 4.5.2 (instead of 4.5.1 in our installation).
2. We are testing on MacOS (latest version 10.11.6, "El Capitan"), you tested on Linux and Windows.

I do not think that either of these differences could be responsible for the problem. Aside from those two differences, the installed versions are the same here (esp. the KIELER Lightweight Diagrams, which has to be 0.8.0 and not 0.9.0, see also issue #197).

Could you please check the "View Management Configuration" dialog (open it from the toolbar in your Franca installation). "Enable view management" should be checked, "Show Franca contract" should be checked, and all other items should be unchecked. 

Meanwhile, we will try to reproduce this bug on Windows.

**Comment by LIII-XXII** [comment]
The View Management Configuration dialog is as it should be: options checked are "Enable View Management" and "Show Franca Contract".

Eclipse sent another error report while retrying:
https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/edUtPaKnIDWM7VZwLIO7p8sJSqmC5tro0dP4gZZy7kwUGjItkReN0M5GUN8MY0CV

**Comment by kbirken** [comment]
In the Eclipse error report you linked there is a 0.9.0 version of de.cau.cs.kieler.klighd... AFAIK, this won't work (see issue #197). Can you pls check? Maybe you have to uninstall this package and reinstall the proper version. Uncheck "Show only latest version" while installing.

**Comment by LIII-XXII** [comment]
Strange, the version that I have in Eclipse's Installed Software shows up as 0.8.0.20160216100, plus the date doesn't match in that error report: 0.9 is supposed to be 201607, not 201602...

Anyway, I tried uninstalling and reinstalling Kieler Lightweight. I still have the problem, and the package list shows the 0.8.0 version:
```
  KIELER Lightweight Diagrams - Developer Resources & Examples	0.8.0.201602161004	de.cau.cs.kieler.klighd.sdk.feature.feature.group	Kiel University
    Eclipse Java Development Tools	3.12.0.v20160606-1100	org.eclipse.jdt.feature.group	Eclipse.org
    Eclipse Platform	4.6.0.v20160606-1342	org.eclipse.platform.feature.group	Eclipse.org
    KIELER Layout API	0.20.0.201602161004	de.cau.cs.kieler.kiml.feature.feature.group	Kiel University
      EMF - Eclipse Modeling Framework Core Runtime	2.12.0.v20160420-0247	org.eclipse.emf.ecore.feature.group	Eclipse Modeling Project
      EMF Common	2.12.0.v20160420-0247	org.eclipse.emf.common.feature.group	Eclipse Modeling Project
      EMF Edit	2.12.0.v20160526-0356	org.eclipse.emf.edit.feature.group	Eclipse Modeling Project
    KIELER Layout API (Sources)	0.20.0.201602161004	de.cau.cs.kieler.kiml.feature.source.feature.group	Kiel University
    KIELER Lightweight Diagrams - Developer Resources & Examples (Sources)	0.8.0.201602161004	de.cau.cs.kieler.klighd.sdk.feature.source.feature.group	Kiel University
    KIELER Lightweight Diagrams Runtime	0.10.0.201602161004	de.cau.cs.kieler.klighd.feature.feature.group	Kiel University
    KIELER Lightweight Diagrams Runtime (Sources)	0.10.0.201602161004	de.cau.cs.kieler.klighd.feature.source.feature.group	Kiel University
    Source for EMF - Eclipse Modeling Framework Core Runtime	2.12.0.v20160420-0247	org.eclipse.emf.ecore.source.feature.group	Eclipse Modeling Project
    Source for EMF Common	2.12.0.v20160420-0247	org.eclipse.emf.common.source.feature.group	Eclipse Modeling Project
    UML2 End-User Features	5.2.0.v20160516-0939	org.eclipse.uml2.feature.group	Eclipse Modeling Project
    Xtend IDE	2.10.0.v201605250459	org.eclipse.xtend.sdk.feature.group	Eclipse Xtend
```

**Comment by kbirken** [comment]
It seems now you have even 0.10.0 plug-ins of KIELER, e.g., "KIELER Lightweight Diagrams Runtime 0.10.0.201602161004". Can you check, pls?

**Comment by kbirken** [comment]
One off-topic question, why do you always close the issue and re-open it again? You can add a comment without closing the issue just by pressing the "Comment" button.

**Comment by LIII-XXII** [comment]
Yes, the KIELER Lightweight Diagrams Runtime 0.10.0.201602161004 runtime is a dependency of 
KIELER Lightweight Diagrams - Developer Resources & Examples	0.8.0.201602161004.
The version number is different, but the date is the same -- I assume that these version numbers are not tied since they refer to different packages. If you do have a different version though, I can try installing that instead (although AFAIK I can't remove a dependency)

Off-topic: I mistake the green "comment" button with a "cancel" button when I'm not paying attention -- Will be more careful about that.

**Comment by kbirken** [comment]
We did some tests here. It seems the plug-in de.cau.cs.kieler.klighd.ui.view (called "KIELER Diagram View") has to be version 0.2.0, not 0.3.0. Please check the version of this plug-in in your "Help > Installation Details > Plugins". 

It is not quite clear yet how to change this version from 0.3.0 to 0.2.0. One workaround could be to install feature "KIELER Lightweight Diagrams Generic Diagram View" with version 0.2.0 and uninstall it afterwards. This seems to drag the version of the above plug-in to 0.2.0. 

Another hint might be to trigger opening of the deprecated KIELER view. Open "Window > Show View > Other > Kieler > Diagram (Deprecated)". We are not sure yet which of those tweaks is really necessary, but doing both helped in our test installation.

BTW, I guess it doesn't depend on Windows vs. MacOS, it is just the time of installation. 0.3.0 of the plug-in mentioned above probably didn't exist when we initially did the tests for 0.11.0.

**Comment by LIII-XXII** [comment]
I went through the whole installation process again and it finally worked. Thank you.
