### ISSUE TITLE
Validator Error

### ISSUE THREAD

**Issue by Vinayakatk** [franca/franca#206]
Franca Deployment defination for type collection with struct specification throws validation error

2879823 [Worker-35] ERROR org.eclipse.xtext.validation.CompositeEValidator  - Error executing EValidator
java.lang.IllegalArgumentException: The sources EClass 'FDTypes' does not expose the feature 'FDInterface.target'
	at org.eclipse.xtext.validation.FeatureBasedDiagnostic.<init>(FeatureBasedDiagnostic.java:33)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.createDiagnostic(AbstractDeclarativeValidator.java:613)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.acceptError(AbstractDeclarativeValidator.java:556)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.error(AbstractDeclarativeValidator.java:441)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.error(AbstractDeclarativeValidator.java:431)
	at org.franca.deploymodel.dsl.validation.FDeployJavaValidator.reportError(FDeployJavaValidator.java:771)
	at org.franca.deploymodel.dsl.validation.FDeployValidator.checkUsedTypesRoot(FDeployValidator.java:415)
	at org.franca.deploymodel.dsl.validation.FDeployValidator.checkUsedTypes(FDeployValidator.java:365)
	at org.franca.deploymodel.dsl.validation.FDeployJavaValidator.checkPropertiesComplete(FDeployJavaValidator.java:238)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)
	at 
[hj.zip](https://github.com/franca/franca/files/831865/hj.zip)

**Comment by Vinayakatk** [comment]
def private checkUsedTypesRoot (FDRootElement rootElem,
		Collection<FTypeRef> typerefs,
		List<FType> localTypes,
		PropertyDefChecker checker
	) {
		var boolean hasError = false
		val referencedTypes =
			typerefs.map[derived].filterNull
			.filter[it.isDeploymentRelevantType()]
			.toSet
		
		// compute all types which are used locally, but not defined locally
		val nonLocal = referencedTypes.filter[!localTypes.contains(it)].toSet
				
		// check if non-local types are covered by 'use' reference (recursively)
		val fromOthers = rootElem.typeDefinitionsByTransitiveUse

		// find non-local types which are not yet deployed in some 'use'd deploy model
		val remaining = nonLocal.filter[!fromOthers.contains(it)].toSet
		
		// identify those types which need deployment properties
		for(missing : remaining) {
			if (checker.mustBeDefined(missing)) {
				val model = missing.getModel
				reporter.reportError(
					"Deployment for type '" + missing.name + "' is missing, " +
					"add 'use' reference for deployment of package '" + model.name + "'",
					rootElem, FD_INTERFACE__TARGET)
				hasError = true
			}
		}
		
		return hasError
	}

This reportError has FD_INTERFACE__TARGET, which is not a proper reference if the FDRootElement  is typeCollection.  So this has to changed in the implementation
